services:

  webapi:
    build:
      context: .
    ports:
      - "5009:5009"
    restart: unless-stopped
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=127.0.0.1,1433;Database=taskmanagerdb;User Id=sa;Password=Password@1234;TrustServerCertificate=True;
    networks:
      - sqlserver-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1234
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - sqlserver-network

volumes:
  sqlserver-data:
    driver: local

networks:
  sqlserver-network:
    driver: bridge
