name: TaskManagerAPI Pipeline

# Trigger the workflow on push to master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Replace with your target .NET Core version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Run tests for the Domain layer
      - name: Run Domain tests
        run: dotnet test ./TaskManagerAPI/TaskManagerAPI.Domain.UnitTests/TaskManagerAPI.Domain.UnitTests.csproj --no-build --configuration Release
        
      # Run tests for the Infrastructure layer
      - name: Run Infrastructure tests
        run: dotnet test ./TaskManagerAPI/TaskManagerAPI.Infrastructure.UnitTests/TaskManagerAPI.Infrastructure.UnitTests.csproj --no-build --configuration Release
